### ISSUE TITLE
点击run按钮 直接报错

### ISSUE THREAD

**Issue by iverson3** [laravel-admin-extensions/scheduling#5]
output 内容：

> In Connection.php line 664:
                                                                               
  SQLSTATE[HY000] [2002] Unknown error while connecting (SQL: select `name`,   
  `value` from `admin_config`)                                                 
                                                                               

In Connector.php line 67:
                                                         
  SQLSTATE[HY000] [2002] Unknown error while connecting

**Comment by ipusi** [comment]
数据库连接问题，检查php pdo_mysql 模块

**Comment by namexd** [comment]
使用command方法打开页面报错。Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@php.cn to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
使用call方法倒是没错
