### ISSUE TITLE
SSL load

### ISSUE THREAD

**Issue by uacode** [laravel-admin-extensions/scheduling#6]
Hello, I think I found a bug...

```
$(function () {
        $('.run-task').click(function (e) {
            var id = $(this).data('id');
            NProgress.start();
            $.ajax({
                method: 'POST',
                url: 'http://XXX.repair/admin/scheduling/run',
                data: {id: id, _token: LA.token},
                success: function (data) {
                    if (typeof data === 'object') {
                        $('.output-box').removeClass('hide');
                        $('.output-box .output-body').html(data.data);
                    }
                    NProgress.done();
                }
            });
        });
    });
```

> jQuery-2.1.4.min.js:4 Mixed Content: The page at 'https://XXX.repair/admin/scheduling' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://XXX.repair/admin/scheduling/run'. This request has been blocked; the content must be served over HTTPS.

In admin config
'secure' => TRUE,

**Comment by z-song** [comment]
Please feel free to send a pr.

**Comment by uacode** [comment]
Will be fixed after merge https://github.com/z-song/laravel-admin/pull/2587
